In [1]:
import json
import pathlib

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
DIRECTORY = pathlib.Path("~/Box/dsi-core/11th-hour/good-food-purchasing/nov2025-dataset").expanduser()

In [3]:
columns = [
    "Food Product Group",
    "Food Product Category",
    "Primary Food Product Category",
    "Basic Type",
    "Sub-Type",
    "Flavor/Cut",
    "Shape",
    "Skin",
    "Seed/Bone",
    "Processing",
    "Cooked/Cleaned",
    "WG/WGR",
    "Dietary Concern",
    "Additives",
    "Dietary Accommodation",
    "Frozen",
    "Packaging",
    "Commodity",
]
column_data = {f"want_{c}": [] for c in columns} | {f"got_{c}": [] for c in columns}

with open(DIRECTORY / "test-results-try3.jsonl") as file:
    for line in file:
        data = json.loads(line)
        if data["status_code"] != 200 or data["deformed_output"] is not None:
            continue
        expected_output = data["expected_output"]
        actual_output = data["actual_output"]
        for c in columns:
            column_data[f"want_{c}"].append(expected_output.get(c, None))
            column_data[f"got_{c}"].append(actual_output.get(c, None))

df = pd.DataFrame(column_data)

In [4]:
allowed = {
    "Food Product Group": [
        "Produce",
        "Condiments & Snacks",
        "Meat",
        "Bread, Grains & Legumes",
        "Meals",
        "Milk & Dairy",
        "Beverages",
        "Non-Food",
        "Seafood",
    ],
    "Food Product Category": [
        "Condiments & Snacks",
        "Vegetables",
        "Meals",
        "Fruit",
        "Grain Products",
        "Beverages",
        "Non-Food",
        "Roots & Tubers",
        "Chicken",
        "Beef",
        "Cheese",
        "Pork",
        "Turkey, Other Poultry",
        "Milk & Dairy",
        "Yogurt",
        "Seafood",
        "Legumes",
        "Milk",
        "Eggs",
        "Tree Nuts & Seeds",
        "Rice",
        "Meat",
        "Butter",
        "Fish (Wild)",
        "Fish (Farm-Raised)",
        "Produce",
    ],
    "Primary Food Product Category": [
        "Condiments & Snacks",
        "Vegetables",
        "Fruit",
        "Grain Products",
        "Beverages",
        "Non-Food",
        "Cheese",
        "Roots & Tubers",
        "Meals",
        "Beef",
        "Chicken",
        "Pork",
        "Turkey, Other Poultry",
        "Milk & Dairy",
        "Seafood",
        "Yogurt",
        "Legumes",
        "Milk",
        "Eggs",
        "Tree Nuts & Seeds",
        "Rice",
        "Butter",
        "Fish (Wild)",
        "Fish (Farm-Raised)",
        "Produce",
        "Meat",
        "Egg",
        "Meats",
    ],
    "Basic Type": df["want_Basic Type"].value_counts().index.tolist(),
    "Flavor/Cut": [
        "flavored",
        "breast",
        "ham",
        "wing",
        "thigh",
        "steak",
        "loin",
        "rib",
        "mix",
        "tenderloin",
        "leg",
        "brisket",
        "chuck",
        "butt",
        "sirloin",
        "shoulder",
        "short rib",
        "bottom round",
        "belly",
        "shank",
        "oxtail",
        "skirt",
        "tri tip",
        "striploin",
        "knuckle",
        "rack",
        "shortloin",
        "cheek",
        "neck",
        "round",
        "tripe",
        "tongue",
        "teres major",
        "pectoral meat",
        "outside skirt",
        "marrow bone",
        "loin rib",
        "t-bone",
        "cut",
    ],
    "Shape": [
        "cut",
        "patty",
        "ground",
        "concentrate",
        "bacon",
        "hot dog",
        "meatball",
        "thickened",
        "crumble",
        "nugget",
        "jerky",
        "salami",
        "pepperoni",
        "pastrami",
        "bologna",
        "prosciutto",
        "shredded",
        "genoa",
        "liquid",
        "mortadella",
        "capocollo",
        "pancetta",
        "bresaola",
        "sopressata",
        "breast",
        "cotto",
        "guanciale",
        "nostrano",
    ],
    "Skin": [
        "skin on",
        "tail on",
        "shell on",
    ],
    "Seed/Bone": [
        "bone-in",
        "pitted",
    ],
    "Processing": [
        "breaded",
        "in juice",
        "seasoned",
        "dried",
        "in syrup",
        "puree",
        "powder",
        "in water",
        "battered",
        "hard boiled",
        "dehydrated",
        "whipped",
        "grated",
        "corned",
        "in sauce",
        "stuffed",
        "in brine",
        "in oil",
        "evaporated",
        "in puree",
        "in vinegar",
        "in liquid",
        "in gel",
        "marinated",
        "powdered",
        "in vegetable broth",
    ],
    "Cooked/Cleaned": [
        "cooked",
        "smoked",
    ],
    "WG/WGR": [
        "whole grain rich",
    ],
    "Dietary Concern": [
        "nonfat",
        "low sodium",
        "low fat",
        "1%",
        "salted",
        "unsalted",
        "decaffeinated",
        "diet",
        "2%",
        "reduced sodium",
        "fat free",
        "reduced sugar",
        "no sodium",
        "reduced calorie",
        "caffeinated",
    ],
    "Additives": [
        "no additives",
        "unsweetened",
        "additives",
        "sweetened",
    ],
    "Dietary Accommodation": [
        "gluten free",
        "kosher",
        "vegan",
        "vegetarian",
        "lactose free",
        "halal",
        "non-dairy",
    ],
    "Frozen": [
        "frozen",
        "iced",
    ],
    "Packaging": [
        "ss",
        "canned",
        "jarred",
    ],
    "Commodity": [
        "commodity",
    ],
}

In [5]:
p_correct = {}

In [6]:
def want_and_got(column):
    mapping = {x: x for x in allowed[column]} | {None: "(missing)", "": "(missing)"}
    want = df[f"want_{column}"].map(lambda x: mapping.get(x, "(malformed)"))
    got = df[f"got_{column}"].map(lambda x: "malformed" if isinstance(x, list) else mapping.get(x, "(malformed)"))
    print("malformed values:")
    print(np.unique(df[f"got_{column}"][got == "(malformed)"]))
    return want, got

In [7]:
def confusion_matrix(column):
    print(column)
    print("-" * 80)

    want, got = want_and_got(column)
    table = pd.crosstab(want, got, margins=True, margins_name="(total)")

    print("-" * 80)
    nottotal = [x for x in table.columns if x != "(total)"]
    probtable = pd.DataFrame({
        "P(output)": [100 * table[x].loc["(total)"] / table["(total)"].loc["(total)"] for x in nottotal],
        "P(correct)": [100 * (0 if x not in table.index else table[x].loc[x]) / table[x].loc["(total)"] for x in nottotal],
    }, index=nottotal)
    print(probtable)
    print("-" * 80)
    overall = 100 * np.count_nonzero(want == got) / len(df)
    print(f"overall P(correct): {overall:9.5f}%")
    print()
    p_correct[column] = {
        "overall": overall,
        "byvalue": {
            "" if index == "(missing)" else index: row["P(correct)"]
            for index, row in probtable.iterrows()
            if index != "(malformed)"
        },
        "numsamples": {
            "" if index == "(missing)" else index: int(row["P(correct)"] * table[index].loc["(total)"] / 100)
            for index, row in probtable.iterrows()
            if index != "(malformed)"
        },
    }

    middle = table[[x for x in table.columns if not x.startswith("(")]].loc[[x for x in table.index if not x.startswith("(")]]

    table.index.name = "want:"
    table.columns.name = "got:"
    return table.style.background_gradient(cmap="Blues", vmin=0, vmax=middle.max().max())

In [8]:
confusion_matrix("Food Product Group")

Food Product Group
--------------------------------------------------------------------------------
malformed values:
['Beans' 'Beef' 'Butter' 'Butter, Eggs & Other' 'Butter, Oil & Condiments'
 'Butter, Other Dairy' 'Cheese' 'Chicken' 'Chicken, Other Poultry'
 'Commodity' 'Dairy' 'Desserts' 'Eggs' 'Fish (Farm-Raised)' 'Fruit'
 'Grain Products' 'Legumes' 'Meet' 'Mine' 'Plant-Based' 'Pork' 'Potatoes'
 'Poultry' 'Protein' 'Protein Foods' 'Rice' 'Roots & Tubers' 'Sandwiches'
 'Soy' 'Tree Nuts & Seeds' 'Turkey, Other Poultry' 'Vegetables' 'WG/WGR']
--------------------------------------------------------------------------------
                         P(output)  P(correct)
(malformed)              15.297998    0.000000
(missing)                 0.004550    0.000000
Beverages                 5.962238   94.353300
Bread, Grains & Legumes   6.813012   94.624374
Condiments & Snacks      26.280710   84.281139
Meals                     6.146497   88.823094
Meat                      3.798908   85.928144
Milk & Dairy              6.294359   92.374413
Non-Food                  5.545951   96.882691
Produce                  22.158781   94.394826
Seafood                   1.696997   90.750670
--------------------------------------------------------------------------------
overall P(correct):  76.59008%

In [9]:
confusion_matrix("Food Product Category")

Food Product Category
--------------------------------------------------------------------------------
malformed values:
['Beans' 'Bread, Grain & Legumes' 'Bread, Grain Products'
 'Bread, Grain Products & Legumes' 'Bread, Grains & Legumes'
 'Butter, Oil & Condiments' 'Butter, Other Dairy' 'Cereal' 'Commodity'
 'Dessert' 'Desserts' 'Duck' 'Egg' 'Herbs' 'Herbs & Spices' 'Pizza'
 'Plant-Based' 'Potato' 'Potatoes' 'Root & Tubers' 'Seed/Nut' 'Soy'
 'Soy Products' 'Squash' 'Veal' 'WG/WGR']
--------------------------------------------------------------------------------
                       P(output)  P(correct)
(malformed)             0.461783    0.000000
Beef                    4.192448   69.234943
Beverages               5.950864   94.495413
Butter                  0.418562   61.413043
Cheese                  4.488171   62.797770
Chicken                 4.210646   78.660184
Condiments & Snacks    25.618744   86.236903
Eggs                    1.105551   63.991770
Fish (Farm-Raised)      0.070519   16.129032
Fish (Wild)             0.034122   60.000000
Fruit                   8.830755   95.466255
Grain Products          5.746133   93.151227
Legumes                 1.041856   88.209607
Meals                   3.516833   84.217335
Meat                    0.138763   27.868852
Milk                    1.096451   87.344398
Milk & Dairy            1.246588   83.394161
Non-Food                5.555050   96.764947
Pork                    2.147407   88.983051
Produce                 1.096451    2.697095
Rice                    0.559600   82.113821
Roots & Tubers          4.358508   72.390397
Seafood                 1.626479   66.013986
Tree Nuts & Seeds       0.659691   85.517241
Turkey, Other Poultry   2.008644   79.048698
Vegetables             12.602366   82.148014
Yogurt                  1.217015   97.196262
--------------------------------------------------------------------------------
overall P(correct):  83.13694%

In [10]:
confusion_matrix("Primary Food Product Category")

Primary Food Product Category
--------------------------------------------------------------------------------
malformed values:
['Beans' 'Bread, Grain & Legumes' 'Bread, Grain Products'
 'Bread, Grain Products & Legumes' 'Bread, Grains & Legges'
 'Bread, Grains & Legumes' 'Butter, Oil & Condiments'
 'Butter, Other Dairy' 'Commodity' 'Dessert' 'Desserts' 'Duck' 'Herbs'
 'Herbs & Spices' 'Pizza' 'Plant-Based' 'Potato' 'Potatoes' 'Seed/Nut'
 'Soy' 'Soy Products' 'Squash' 'Tuna (Farm-Raised)' 'Veal' 'Veggie'
 'WG/WGR']
--------------------------------------------------------------------------------
                       P(output)  P(correct)
(malformed)             0.420837    0.000000
(missing)               3.560055    0.063898
Beef                    4.292539   90.302067
Beverages               5.773430   94.562648
Butter                  0.386715   62.352941
Cheese                  4.870337   91.219057
Chicken                 4.274340   94.571581
Condiments & Snacks    24.808917   86.456996
Egg                     0.038672    0.000000
Eggs                    0.948590   75.539568
Fish (Farm-Raised)      0.079618   22.857143
Fish (Wild)             0.043221   57.894737
Fruit                   8.516833   95.272436
Grain Products          5.527753   93.045267
Legumes                 1.028207   88.053097
Meals                   2.616015   74.956522
Meat                    0.075068    6.060606
Milk                    1.098726   87.370600
Milk & Dairy            1.203367   83.931947
Non-Food                4.447225   96.214834
Pork                    2.136033   95.420660
Produce                 1.071429    2.335456
Rice                    0.550500   82.231405
Roots & Tubers          4.294813   72.881356
Seafood                 1.576433   75.613276
Tree Nuts & Seeds       0.643767   85.159011
Turkey, Other Poultry   2.013194   86.214689
Vegetables             12.490901   82.079767
Yogurt                  1.212466   97.373358
--------------------------------------------------------------------------------
overall P(correct):  83.20519%

In [11]:
confusion_matrix("Basic Type")
None

Basic Type
--------------------------------------------------------------------------------
malformed values:
['addon' 'alcohol' 'alcoholic beverage' 'almond' 'anise' 'apple butter'
 'apple sauce' 'artichoke heart' 'auce' 'bas' 'bean salad' 'beans'
 'beef alternative' 'beef chili' 'beef frank' 'beef sub' 'beef substitute'
 'beefaroni' 'beefless' 'beer' 'bell pepper' 'beverage' 'bicarbonate'
 'black bean' 'blend' 'bouillon' 'bread pudding' 'broccoli slaw' 'burgers'
 'cake' 'calzonette' 'candy bar' 'cannoli' 'cantaloupe' 'caperberry'
 'capers' 'cheeseburger' 'cheesecake' 'chicken alternative' 'chili pepper'
 'chili relleno' 'chimi' 'chipotle' 'chipotle sauce' 'chive' 'chocolate'
 'cinnamon raisin' 'cinnamon toast' 'coating' 'cocktail' 'cocoa'
 'cocoa mix' 'coffee bean' 'cola' 'coleslaw' 'collard' 'coloring'
 'corn chip' 'corn meal' 'corn nut' 'cornflake' 'cornish hen' 'cornstarch'
 'cotton candy' 'covering' 'crackers' 'craisins' 'cranberry dried'
 'crayfish' 'crema' 'crumb' 'crumble' 'cup' 'daikon' 'danish'
 'dietary accommodation' 'dinner' 'donut' 'dough conditioner'
 'dressing Italian' 'drink mix' 'edible flower' 'egg nog' 'egg noodle'
 'egg sandwich' 'eggnog' 'eggplant parmesan' 'eggs salad' 'eggsalad'
 'entr' 'entr e' 'entr%C3%A9e' 'entr&#233;e' 'entr\\u00c3\\u00a9e'
 'entr__food' 'entrance' 'espresso' 'fat' 'fettuccini' 'flavored milk'
 'flour tortilla' 'focaccia' 'food thickener' 'formula' 'frank'
 'french toast stick' 'fries' 'frozen' 'fruit bowl' 'fruit leather'
 'fruit puree' 'fruit roll' 'fruit rollup' 'fry' 'fudge' 'fuel'
 'garlic powder' 'gel' 'ginger root' 'grain' 'granola bar'
 'granola cluster' 'grape juice' 'greens' 'gum' 'gyros' 'hen' 'honeydew'
 'hushpuppy' 'ice cream sandwich' 'ice pop' 'infant formula' 'ingredient'
 'jalapeno popper' 'jam' 'jerky' 'juice cocktail' 'juice concentrate'
 'juice pop' 'jujce' 'jujube' 'kiwiberry' 'lavash' 'leaf' 'leather'
 'lemon grass' 'lo mein' 'lobster bisque' 'macaroni and cheese with bacon'
 'macaroon' 'mahi' 'mahi-mahi' 'mandarin orange' 'marinade' 'marshmallow'
 'mesa' 'microgreens' 'milk alternative' 'milk substitute' 'milkshake'
 'minneola' 'miso' 'mousse' 'musaceae' 'mustard' 'musubi' 'naan' 'nectar'
 'nut butter' 'nut mix' 'nutmeg' 'oleo' 'orange chicken' 'orzo'
 'palm heart' 'pan coating' 'pangasius swai' 'papadum' 'paprika'
 'passion fruit' 'pasta salad' 'pastrami' 'pasty' 'pea and carrot'
 'peanut butter powder' 'pie shell' 'pilaf' 'pizza dough' 'plant based'
 'plant drink' 'plant-based' 'pomegranate seed' 'pop' 'pop tart'
 'prickly pear' 'protein supplement' 'pudding' 'puff' 'pumpernickel'
 'rangoon' 'rangoons' 'relish' 'rice cake' 'rice noodle' 'romaine'
 'salad dressing' 'salad mix' 'salisbury steak' 'salmon alternative'
 'sauerkraut' 'sesame' 'shellfish' 'sidekick' 'skin' 'slaw' 'snack mix'
 'soup base' 'soy' 'soy milk' 'soybean' 'spanakopita' 'spring mix' 'squid'
 'starfruit' 'stick' 'straw' 'stuffed' 'sub' 'sugar alternative'
 'sunflower seed butter' 'supper kit' 'supplement shake' 'swai'
 'sweet potato' 'swine' 'tart' 'toast' 'toast french' 'tomato paste'
 'tongue' 'tostada' 'trail mix' 'tree nut' 'turmeric' 'turnip green'
 'ugli fruit' 'vegetable blend' 'vegetable oil' 'veggie' 'wheat']
--------------------------------------------------------------------------------
             P(output)  P(correct)
(malformed)   1.014559    0.000000
(missing)    12.656961   43.044572
additive      0.002275    0.000000
additives     0.009099   25.000000
appetizer     0.068244   56.666667
...                ...         ...
yam           0.006824   33.333333
yeast         0.027298   91.666667
yogurt        1.148772   95.841584
yucca         0.011374   60.000000
zucchini      0.036397   12.500000

[436 rows x 2 columns]
--------------------------------------------------------------------------------
overall P(correct):  77.82530%

In [12]:
confusion_matrix("Flavor/Cut")

Flavor/Cut
--------------------------------------------------------------------------------
malformed values:
['all' 'bacon' 'banana' 'barbecue' 'base' 'beef' 'blueberry' 'bone-in'
 'brat' 'buttermilk' 'cap' 'capicola' 'cheese' 'chicken' 'chip'
 'chocolate' 'chop' 'clod' 'cream' 'cup' 'dark' 'dark meat' 'drum'
 'drumette' 'drumstick' 'fajita' 'feet' 'flank' 'flank steak' 'flap'
 'flat iron' 'foot' 'grated' 'hanger' 'heart' 'hindshank' 'honey'
 'hot dog' 'iced' 'inch' 'inside round' 'inside skirt' 'link' 'marinated'
 'no sodium' 'ox tail' 'pepperoni' 'picnic' 'pork' 'prime rib' 'pulled'
 'quarter' 'ribeye' 'roast' 'salted' 'sausage' 'seasoned' 'sharp'
 'shredded' 'skin on' 'smoked' 'spicy' 'strawberry' 'stuffed' 'substitute'
 'tail' 'tender' 'thickened' 'tip' 'top inside round' 'top round'
 'top sirloin' 'vanilla' 'variety']
--------------------------------------------------------------------------------
               P(output)  P(correct)
(malformed)     0.520928    0.000000
(missing)      93.919472   93.339308
belly           0.013649  100.000000
bottom round    0.063694   32.142857
breast          1.430846   88.076312
brisket         0.118289   86.538462
butt            0.100091   81.818182
cheek           0.013649   83.333333
chuck           0.109190   70.833333
cut             0.113740    0.000000
flavored        1.665150   65.163934
ham             0.373066   82.317073
knuckle         0.011374  100.000000
leg             0.127389   76.785714
loin            0.197907   75.862069
malformed       0.004550    0.000000
mix             0.063694    3.571429
neck            0.006824   66.666667
outside skirt   0.009099   25.000000
oxtail          0.022748  100.000000
pectoral meat   0.004550  100.000000
rack            0.011374  100.000000
rib             0.138763   70.491803
round           0.020473    0.000000
shank           0.011374  100.000000
short rib       0.029572   84.615385
shortloin       0.009099  100.000000
shoulder        0.034122   93.333333
sirloin         0.075068   75.757576
skirt           0.011374   40.000000
steak           0.068244   36.666667
striploin       0.015924   71.428571
tenderloin      0.131938   53.448276
teres major     0.018198   25.000000
thigh           0.227480   91.000000
tongue          0.004550  100.000000
tri tip         0.018198   50.000000
wing            0.284349   98.400000
--------------------------------------------------------------------------------
overall P(correct):  91.77889%

In [13]:
confusion_matrix("Shape")

Shape
--------------------------------------------------------------------------------
malformed values:
['aroma' 'bagel' 'bar' 'battered' 'beef' 'belly' 'breaded' 'bun' 'cake'
 'cheese' 'chewy' 'chip' 'coarse' 'cone' 'corn dog' 'corned' 'croissant'
 'crumb' 'crumbled' 'crushed' 'crust' 'cup' 'curd' 'cut. Cooked' 'dough'
 'doughnut' 'dried' 'drumstick' 'eggs' 'empanada' 'frank' 'fritter'
 'grated' 'ham' 'hamburger' 'hash' 'hash brown' 'iced' 'in water' 'juice'
 'knockwurst' 'link' 'mashed' 'meat' 'meatloaf' 'mix' 'noodle' 'pancake'
 'pasta' 'paste' 'pie' 'pork' 'portion' 'powder' 'protein' 'puree' 'rib'
 'rip' 'roll' 'salad' 'sandwich' 'sausage' 'scramble' 'scrambled'
 'seasoned' 'short rib' 'skin on' 'sparerib' 'ss' 'steak' 'stick'
 'stuffed' 'sub' 'summer sausage' 'taco' 'taquito' 'tater tot'
 'tenderloin' 'wafer' 'whipped' 'wing']
--------------------------------------------------------------------------------
             P(output)  P(correct)
(malformed)   0.723385    0.000000
(missing)    82.409008   94.368841
bacon         0.352593   90.322581
bologna       0.045496   85.000000
bresaola      0.002275  100.000000
capocollo     0.004550   50.000000
concentrate   0.145587   23.437500
crumble       0.170610   76.000000
cut          12.015469   75.785687
ground        1.080528   60.000000
hot dog       0.384440   49.704142
jerky         0.097816   46.511628
liquid        0.011374    0.000000
meatball      0.313922   90.579710
mortadella    0.002275  100.000000
nugget        0.216106   76.842105
pastrami      0.025023  100.000000
patty         1.694722   70.738255
pepperoni     0.036397   37.500000
prosciutto    0.006824  100.000000
salami        0.063694   67.857143
shredded      0.177434    5.128205
thickened     0.020473   44.444444
--------------------------------------------------------------------------------
overall P(correct):  90.04322%

In [14]:
confusion_matrix("Skin")

Skin
--------------------------------------------------------------------------------
malformed values:
['casing' 'casings in' 'flavored' 'seeded' 'skinless']
--------------------------------------------------------------------------------
             P(output)  P(correct)
(malformed)   0.043221    0.000000
(missing)    99.410828   99.915334
shell on      0.009099    0.000000
skin on       0.500455   32.727273
tail on       0.036397   56.250000
--------------------------------------------------------------------------------
overall P(correct):  99.51092%

In [15]:
confusion_matrix("Seed/Bone")

Seed/Bone
--------------------------------------------------------------------------------
malformed values:
['boneless' 'natural casing' 'seeded' 'skinless' 'tail on']
--------------------------------------------------------------------------------
             P(output)  P(correct)
(malformed)   0.036397    0.000000
(missing)    99.372157   99.935903
bone-in       0.323021   29.577465
pitted        0.268426   25.423729
--------------------------------------------------------------------------------
overall P(correct):  99.47225%

In [16]:
confusion_matrix("Processing")

Processing
--------------------------------------------------------------------------------
malformed values:
['additives' 'aged' 'baked' 'barbecue' 'blanched' 'blend' 'canned'
 'chilled' 'classic' 'concentrate' 'condensed' 'cook' 'cooked' 'creamed'
 'crumb' 'crumbled' 'crushed' 'cured' 'cut' 'decaffeinated' 'diluted'
 'dry' 'enriched' 'extra firm' 'floret' 'fresh' 'fried' 'frozen'
 'gluten free' 'grilled' 'ground' 'homogenized' 'iced' 'in broth'
 'in chocolate' 'in concentrate' 'in cream' 'in dressing' 'in gravy'
 'in jelly' 'in liquor' 'in mayonnaise' 'in shell' 'in solution' 'instant'
 'jerky' 'liquid' 'low fat' 'low moisture' 'low sodium' 'mashed'
 'mechanically separated' 'mix' 'omelette' 'par boiled' 'parbaked'
 'parboiled' 'partially cooked' 'pasteurized' 'pastrami' 'peeled'
 'pre-fried' 'precooked' 'precut' 'pressed' 'processed' 'prosciutto'
 'ready to eat' 'reduced calorie' 'reduced sugar' 'refried' 'rendered'
 'roasted' 'salted' 'sauce' 'scrambled' 'seedless' 'serving' 'shredded'
 'smoked' 'sour' 'ss' 'substitute' 'sugared' 'sweetened' 'thickened'
 'toasted' 'ultra pasteurized' 'unflavored' 'unsalted' 'unsweetened'
 'washed']
--------------------------------------------------------------------------------
                    P(output)  P(correct)
(malformed)          1.003185    0.000000
(missing)           91.983621   98.127906
battered             0.168335   59.459459
breaded              1.389900   77.741408
corned               0.086442   84.210526
dehydrated           0.075068   57.575758
dried                1.062329   37.259101
evaporated           0.022748   90.000000
grated               0.095541   88.095238
hard boiled          0.034122   80.000000
in brine             0.097816   30.232558
in juice             0.850773   57.219251
in liquid            0.009099    0.000000
in oil               0.054595   37.500000
in puree             0.065969   17.241379
in sauce             0.220655   10.309278
in syrup             0.282075   66.935484
in vegetable broth   0.002275    0.000000
in vinegar           0.013649    0.000000
in water             0.320746   52.482270
marinated            0.006824    0.000000
powder               0.327571   29.166667
powdered             0.056870    0.000000
puree                0.320746   48.226950
seasoned             1.348954   15.514334
stuffed              0.040946   16.666667
whipped              0.059145   84.615385
--------------------------------------------------------------------------------
overall P(correct):  93.53048%

In [17]:
confusion_matrix("Cooked/Cleaned")

Cooked/Cleaned
--------------------------------------------------------------------------------
malformed values:
['breaded' 'cleaned' 'dehydrated' 'fried' 'hard boiled' 'iced' 'parfried'
 'pasteurized' 'raw' 'ready to eat' 'seasoned']
--------------------------------------------------------------------------------
             P(output)  P(correct)
(malformed)   0.040946    0.000000
(missing)    94.071884   98.551531
cooked        5.168335   59.771127
smoked        0.718835   51.265823
--------------------------------------------------------------------------------
overall P(correct):  96.16697%

In [18]:
confusion_matrix("WG/WGR")

WG/WGR
--------------------------------------------------------------------------------
malformed values:
['1%' 'ss']
--------------------------------------------------------------------------------
                  P(output)  P(correct)
(malformed)        0.009099    0.000000
(missing)         94.717925   98.508574
whole grain rich   5.272975   82.786885
--------------------------------------------------------------------------------
overall P(correct):  97.67061%

In [19]:
confusion_matrix("Dietary Concern")

Dietary Concern
--------------------------------------------------------------------------------
malformed values:
['10%' '3% milkfat' 'additives' 'dietary accommodation' 'dieted'
 'dietetic' 'extra lean' 'full fat' 'gluten free' 'kosher' 'lactose free'
 'lean' 'low calorie' 'low milkfat' 'low moisture' 'low sugar' 'no sugar'
 'reduced' 'reduced fat' 'salt free' 'special diet' 'unsweetened' 'whole'
 'whole milk' 'zero trans fat']
--------------------------------------------------------------------------------
                 P(output)  P(correct)
(malformed)       0.152411    0.000000
(missing)        95.907643   99.255236
1%                0.373066   74.390244
2%                0.225205   83.838384
caffeinated       0.006824    0.000000
decaffeinated     0.172884   78.947368
diet              0.186533   40.243902
fat free          0.100091   20.454545
low fat           0.605096   47.368421
low sodium        0.846224   62.903226
no sodium         0.061419    3.703704
nonfat            0.807552   79.436620
reduced calorie   0.027298   25.000000
reduced sodium    0.138763   50.819672
reduced sugar     0.029572   15.384615
salted            0.177434   70.512821
unsalted          0.181984   58.750000
--------------------------------------------------------------------------------
overall P(correct):  97.66833%

In [20]:
confusion_matrix("Additives")

Additives
--------------------------------------------------------------------------------
malformed values:
['reduced' 'salted' 'unsalted']
--------------------------------------------------------------------------------
              P(output)  P(correct)
(malformed)    0.015924    0.000000
(missing)     98.682894   99.183975
additives      0.111465    0.000000
no additives   0.348044    0.653595
sweetened      0.052320    4.347826
unsweetened    0.789354   26.224784
--------------------------------------------------------------------------------
overall P(correct):  98.08917%

In [21]:
confusion_matrix("Dietary Accommodation")

Dietary Accommodation
--------------------------------------------------------------------------------
malformed values:
['decaffeinated' 'diet' 'soy free']
--------------------------------------------------------------------------------
              P(output)  P(correct)
(malformed)    0.006824    0.000000
(missing)     98.491811   99.538074
gluten free    0.743858   64.831804
halal          0.104641   82.608696
kosher         0.266151   52.136752
lactose free   0.054595   79.166667
non-dairy      0.029572    0.000000
vegan          0.161510   42.253521
vegetarian     0.141037   43.548387
--------------------------------------------------------------------------------
overall P(correct):  98.91720%

In [22]:
confusion_matrix("Frozen")

Frozen
--------------------------------------------------------------------------------
malformed values:
[]
--------------------------------------------------------------------------------
           P(output)  P(correct)
(missing)  92.493176   99.001476
frozen      7.158781   68.541468
iced        0.348044   18.300654
--------------------------------------------------------------------------------
overall P(correct):  96.54004%

In [23]:
confusion_matrix("Packaging")

Packaging
--------------------------------------------------------------------------------
malformed values:
[]
--------------------------------------------------------------------------------
           P(output)  P(correct)
(missing)  86.803913   93.870384
canned      1.710646   69.946809
jarred      0.020473    0.000000
ss         11.464968   68.313492
--------------------------------------------------------------------------------
overall P(correct):  90.51183%

In [24]:
confusion_matrix("Commodity")

Commodity
--------------------------------------------------------------------------------
malformed values:
[]
--------------------------------------------------------------------------------
           P(output)  P(correct)
(missing)  99.160601   99.479250
commodity   0.839399   42.276423
--------------------------------------------------------------------------------
overall P(correct):  98.99909%

In [25]:
print(json.dumps(p_correct, indent=4))

{
    "Food Product Group": {
        "overall": 76.59008189262967,
        "byvalue": {
            "": 0.0,
            "Beverages": 94.35330026707364,
            "Bread, Grains & Legumes": 94.62437395659433,
            "Condiments & Snacks": 84.28113909806977,
            "Meals": 88.82309400444116,
            "Meat": 85.92814371257485,
            "Milk & Dairy": 92.37441272135887,
            "Non-Food": 96.88269073010665,
            "Produce": 94.39482599322452,
            "Seafood": 90.75067024128687
        },
        "numsamples": {
            "": 0,
            "Beverages": 2473,
            "Bread, Grains & Legumes": 2834,
            "Condiments & Snacks": 9737,
            "Meals": 2400,
            "Meat": 1435,
            "Milk & Dairy": 2555,
            "Non-Food": 2362,
            "Produce": 9195,
            "Seafood": 677
        }
    },
    "Food Product Category": {
        "overall": 83.13694267515923,
        "byvalue": {
            "Beef": 69.23494302767227,
            "Beverages": 94.4954128440367,
            "Butter": 61.41304347826087,
            "Cheese": 62.7977698935631,
            "Chicken": 78.66018368449487,
            "Condiments & Snacks": 86.23690285917243,
            "Eggs": 63.991769547325106,
            "Fish (Farm-Raised)": 16.129032258064516,
            "Fish (Wild)": 60.0,
            "Fruit": 95.46625450798557,
            "Grain Products": 93.15122723673792,
            "Legumes": 88.20960698689956,
            "Meals": 84.21733505821474,
            "Meat": 27.868852459016395,
            "Milk": 87.34439834024896,
            "Milk & Dairy": 83.39416058394161,
            "Non-Food": 96.76494676494677,
            "Pork": 88.98305084745763,
            "Produce": 2.6970954356846475,
            "Rice": 82.11382113821138,
            "Roots & Tubers": 72.39039665970772,
            "Seafood": 66.01398601398601,
            "Tree Nuts & Seeds": 85.51724137931035,
            "Turkey, Other Poultry": 79.04869762174405,
            "Vegetables": 82.14801444043322,
            "Yogurt": 97.19626168224299
        },
        "numsamples": {
            "Beef": 1276,
            "Beverages": 2472,
            "Butter": 113,
            "Cheese": 1239,
            "Chicken": 1456,
            "Condiments & Snacks": 9711,
            "Eggs": 311,
            "Fish (Farm-Raised)": 5,
            "Fish (Wild)": 9,
            "Fruit": 3706,
            "Grain Products": 2353,
            "Legumes": 404,
            "Meals": 1302,
            "Meat": 17,
            "Milk": 421,
            "Milk & Dairy": 457,
            "Non-Food": 2363,
            "Pork": 840,
            "Produce": 13,
            "Rice": 202,
            "Roots & Tubers": 1387,
            "Seafood": 472,
            "Tree Nuts & Seeds": 248,
            "Turkey, Other Poultry": 698,
            "Vegetables": 4551,
            "Yogurt": 520
        }
    },
    "Primary Food Product Category": {
        "overall": 83.20518653321201,
        "byvalue": {
            "": 0.06389776357827476,
            "Beef": 90.30206677265501,
            "Beverages": 94.56264775413712,
            "Butter": 62.35294117647059,
            "Cheese": 91.2190565156469,
            "Chicken": 94.57158062799361,
            "Condiments & Snacks": 86.45699614890886,
            "Egg": 0.0,
            "Eggs": 75.53956834532374,
            "Fish (Farm-Raised)": 22.857142857142858,
            "Fish (Wild)": 57.89473684210526,
            "Fruit": 95.2724358974359,
            "Grain Products": 93.04526748971193,
            "Legumes": 88.05309734513274,
            "Meals": 74.95652173913044,
            "Meat": 6.0606060606060606,
            "Milk": 87.37060041407868,
            "Milk & Dairy": 83.93194706994329,
            "Non-Food": 96.21483375959079,
            "Pork": 95.4206602768903,
            "Produce": 2.335456475583864,
            "Rice": 82.23140495867769,
            "Roots & Tubers": 72.88135593220339,
            "Seafood": 75.61327561327562,
            "Tree Nuts & Seeds": 85.15901060070671,
            "Turkey, Other Poultry": 86.21468926553672,
            "Vegetables": 82.07976689127663,
            "Yogurt": 97.37335834896811
        },
        "numsamples": {
            "": 1,
            "Beef": 1704,
            "Beverages": 2400,
            "Butter": 106,
            "Cheese": 1953,
            "Chicken": 1777,
            "Condiments & Snacks": 9429,
            "Egg": 0,
            "Eggs": 315,
            "Fish (Farm-Raised)": 8,
            "Fish (Wild)": 11,
            "Fruit": 3567,
            "Grain Products": 2261,
            "Legumes": 398,
            "Meals": 862,
            "Meat": 2,
            "Milk": 422,
            "Milk & Dairy": 444,
            "Non-Food": 1881,
            "Pork": 896,
            "Produce": 11,
            "Rice": 199,
            "Roots & Tubers": 1376,
            "Seafood": 524,
            "Tree Nuts & Seeds": 241,
            "Turkey, Other Poultry": 763,
            "Vegetables": 4507,
            "Yogurt": 519
        }
    },
    "Basic Type": {
        "overall": 77.8252957233849,
        "byvalue": {
            "": 43.044572250179726,
            "additive": 0.0,
            "additives": 25.0,
            "appetizer": 56.666666666666664,
            "apple": 97.40484429065744,
            "applesauce": 98.4251968503937,
            "apricot": 96.42857142857143,
            "artichoke": 100.0,
            "arugula": 77.77777777777777,
            "asparagus": 100.0,
            "avocado": 100.0,
            "baby food": 100.0,
            "bacon": 7.6923076923076925,
            "bagel": 97.91666666666667,
            "baking powder": 100.0,
            "baking soda": 100.0,
            "bamboo shoot": 80.0,
            "banana": 96.91358024691358,
            "bar": 69.0376569037657,
            "barley": 100.0,
            "barramundi": 100.0,
            "basa": 50.0,
            "base": 94.97206703910615,
            "batter": 85.29411764705883,
            "bean": 85.5691056910569,
            "bean sprout": 84.61538461538461,
            "beef": 83.71621621621621,
            "beet": 97.02970297029702,
            "berry": 40.0,
            "biscuit": 88.40579710144928,
            "bison": 85.71428571428571,
            "blackberry": 100.0,
            "blintz": 87.5,
            "blueberry": 97.95918367346938,
            "bok choy": 100.0,
            "bologna": 0.0,
            "bowl": 28.571428571428573,
            "bread": 78.79377431906615,
            "breadcrumb": 88.88888888888889,
            "breadfruit": 100.0,
            "breadstick": 91.48936170212765,
            "broccoli": 92.89940828402366,
            "broccoli rabe": 50.0,
            "broccolini": 100.0,
            "broth": 82.22222222222223,
            "brussels sprout": 96.0,
            "buffalo": 0.0,
            "bulgur": 100.0,
            "bun": 93.53233830845771,
            "burger": 27.586206896551722,
            "burrito": 97.24770642201835,
            "butter": 77.88461538461539,
            "butter alternative": 100.0,
            "buttermilk": 96.875,
            "cabbage": 90.42553191489361,
            "cactus": 100.0,
            "calzone": 91.66666666666667,
            "candy": 87.16577540106952,
            "caper": 100.0,
            "carrot": 96.37096774193549,
            "catfish": 100.0,
            "cauliflower": 99.08256880733946,
            "celery": 95.3125,
            "celery root": 60.0,
            "cereal": 87.04512372634643,
            "chalupa": 100.0,
            "chard": 77.77777777777777,
            "cheese": 81.36966126656849,
            "cherry": 100.0,
            "chicken": 88.82716049382717,
            "chicken salad": 0.0,
            "chile": 0.0,
            "chile relleno": 100.0,
            "chili": 67.56756756756756,
            "chimichanga": 100.0,
            "chip": 84.08759124087591,
            "chow mein": 0.0,
            "choy sum": 100.0,
            "cilantro": 33.333333333333336,
            "cinnamon roll": 33.333333333333336,
            "clam": 85.71428571428571,
            "clementine": 25.0,
            "cocoa butter": 100.0,
            "cocoa powder": 83.33333333333333,
            "coconut": 90.9090909090909,
            "cod": 100.0,
            "coffee": 88.81118881118881,
            "collard greens": 100.0,
            "condiment": 59.50653120464441,
            "cone": 100.0,
            "cookie": 93.87755102040816,
            "corn": 95.16908212560386,
            "corn dog": 88.23529411764706,
            "corn starch": 100.0,
            "cornbread": 100.0,
            "cornmeal": 86.95652173913044,
            "couscous": 93.33333333333333,
            "crab": 62.5,
            "crab cake": 100.0,
            "crabmeat": 0.0,
            "cracker": 91.71717171717172,
            "cranberry": 100.0,
            "crawfish": 100.0,
            "cream": 70.14925373134328,
            "cream cheese": 90.19607843137256,
            "creamer": 99.33333333333333,
            "crepe": 50.0,
            "croissant": 13.636363636363637,
            "crouton": 100.0,
            "crust": 85.71428571428571,
            "cucumber": 98.53658536585365,
            "date": 100.0,
            "dessert": 70.07700770077008,
            "dim sum": 100.0,
            "dip": 57.142857142857146,
            "dolma": 66.66666666666667,
            "dough": 96.69669669669669,
            "doughnut": 0.0,
            "dragon fruit": 100.0,
            "dressing": 97.85575048732943,
            "drink": 36.090225563909776,
            "duck": 100.0,
            "dumpling": 62.5,
            "edamame": 100.0,
            "egg": 20.0,
            "egg roll": 81.25,
            "egg salad": 50.0,
            "egg substitute": 100.0,
            "eggplant": 95.83333333333333,
            "eggroll": 0.0,
            "eggs": 68.06282722513089,
            "empanada": 95.83333333333333,
            "enchilada": 87.5,
            "endive": 88.88888888888889,
            "energy drink": 100.0,
            "english muffin": 95.83333333333333,
            "entree": 0.0,
            "entr\u00c3\u00a9e": 100.0,
            "extract": 100.0,
            "falafel": 80.0,
            "farro": 100.0,
            "fennel": 94.44444444444444,
            "fig": 100.0,
            "filling": 100.0,
            "fish": 37.878787878787875,
            "flatbread": 63.63636363636363,
            "flavor": 0.0,
            "flavoring": 0.0,
            "flounder": 77.77777777777777,
            "flour": 93.54838709677419,
            "flower": 100.0,
            "fondant": 100.0,
            "food coloring": 100.0,
            "french fry": 95.0,
            "french toast": 92.70833333333333,
            "frittata": 100.0,
            "frosting": 100.0,
            "fruit": 45.78313253012048,
            "fruit cocktail": 58.064516129032256,
            "fruit cup": 38.888888888888886,
            "fruit mix": 0.0,
            "fruit salad": 41.666666666666664,
            "fruit snack": 90.0,
            "garlic": 92.53731343283582,
            "gelatin": 0.0,
            "gelato": 100.0,
            "ginger": 100.0,
            "gooseberry": 100.0,
            "granola": 60.0,
            "grape": 98.58156028368795,
            "grapefruit": 95.34883720930233,
            "gravy": 63.829787234042556,
            "green bean": 94.5945945945946,
            "green onion": 0.0,
            "grenadier": 100.0,
            "grits": 89.47368421052632,
            "guacamole": 90.0,
            "guava": 100.0,
            "haddock": 100.0,
            "halibut": 100.0,
            "ham": 16.666666666666668,
            "hash": 100.0,
            "hash brown": 85.71428571428571,
            "hashbrown": 50.0,
            "hearts of palm": 100.0,
            "herb": 71.22302158273381,
            "hominy": 100.0,
            "honey": 100.0,
            "horseradish": 0.0,
            "hot dog": 66.66666666666667,
            "huckleberry": 100.0,
            "hummus": 5.0,
            "ice cream": 96.58119658119658,
            "icing": 20.0,
            "italian ice": 66.66666666666667,
            "jackfruit": 100.0,
            "jelly": 12.5,
            "jicama": 100.0,
            "juice": 72.9020979020979,
            "juice bar": 0.0,
            "juice cup": 0.0,
            "kale": 95.71428571428571,
            "kimchi": 100.0,
            "kit": 0.0,
            "kiwi": 98.4375,
            "kohlrabi": 100.0,
            "kolache": 100.0,
            "kombucha": 85.71428571428571,
            "lamb": 94.73684210526316,
            "lasagna": 77.35849056603773,
            "leek": 87.5,
            "lemon": 95.0,
            "lemongrass": 0.0,
            "lentil": 100.0,
            "lettuce": 95.5607476635514,
            "lime": 100.0,
            "loaf": 80.0,
            "lobster": 100.0,
            "lotus root": 100.0,
            "luau leaf": 100.0,
            "lychee": 100.0,
            "mac and cheese": 0.0,
            "macaroni": 45.09803921568628,
            "macaroni and cheese": 16.666666666666668,
            "macaroni salad": 20.0,
            "mackerel": 100.0,
            "mahi mahi": 75.0,
            "mandarin": 81.81818181818181,
            "mango": 95.65217391304348,
            "manicotti": 50.0,
            "margarine": 97.10144927536231,
            "meal": 18.51851851851852,
            "meal kit": 63.63636363636363,
            "meat": 0.0,
            "meatball": 0.0,
            "meatless": 83.01886792452831,
            "meatloaf": 0.0,
            "melon": 96.84210526315789,
            "microgreen": 66.66666666666667,
            "milk": 91.0386965376782,
            "mix": 73.86363636363636,
            "molasses": 100.0,
            "muesli": 100.0,
            "muffin": 86.92579505300354,
            "mushroom": 99.41176470588235,
            "mussel": 100.0,
            "mustard greens": 50.0,
            "nectarine": 100.0,
            "noodle": 74.0,
            "nut": 77.10843373493977,
            "oat": 96.29629629629629,
            "oatmeal": 30.76923076923077,
            "octopus": 100.0,
            "oil": 96.3963963963964,
            "okra": 93.33333333333333,
            "olive": 100.0,
            "omelette": 92.10526315789474,
            "onion": 93.29140461215933,
            "onion ring": 100.0,
            "orange": 86.51162790697674,
            "oregano": 0.0,
            "oyster": 100.0,
            "pancake": 92.45283018867924,
            "pangasius": 100.0,
            "papaya": 100.0,
            "parfait": 50.0,
            "parsnip": 100.0,
            "pasta": 84.90566037735849,
            "paste": 79.74683544303798,
            "pastry": 76.88888888888889,
            "patty": 45.0,
            "pea": 66.97247706422019,
            "pea shoot": 0.0,
            "peach": 95.30201342281879,
            "peanut": 0.0,
            "peanut butter": 90.3225806451613,
            "pear": 99.46524064171123,
            "pepper": 91.78082191780823,
            "pepperoncini": 20.0,
            "pepperoni": 16.666666666666668,
            "persimmon": 100.0,
            "pickle": 0.0,
            "pie": 8.333333333333334,
            "pierogi": 100.0,
            "pineapple": 97.12230215827338,
            "pinwheel": 0.0,
            "pizza": 92.3444976076555,
            "plant milk": 95.62043795620438,
            "plantain": 75.0,
            "plum": 95.0,
            "pluot": 100.0,
            "polenta": 85.71428571428571,
            "pollock": 94.38202247191012,
            "pomegranate": 100.0,
            "popcorn": 90.9090909090909,
            "popsicle": 68.75,
            "pork": 90.44665012406948,
            "pot pie": 66.66666666666667,
            "pot roast": 0.0,
            "potato": 67.45867768595042,
            "potato salad": 60.0,
            "potato skin": 0.0,
            "potpie": 0.0,
            "potsticker": 91.66666666666667,
            "powder": 0.0,
            "preserve": 25.0,
            "pretzel": 29.62962962962963,
            "protein shake": 100.0,
            "prune": 100.0,
            "pumpkin": 88.46153846153847,
            "pupusa": 100.0,
            "puree": 31.147540983606557,
            "quesadilla": 100.0,
            "quiche": 93.75,
            "quinoa": 93.10344827586206,
            "radicchio": 80.0,
            "radish": 97.77777777777777,
            "raisin": 89.36170212765957,
            "ramen": 66.66666666666667,
            "raspberry": 100.0,
            "ravioli": 88.88888888888889,
            "rhubarb": 100.0,
            "rice": 92.35668789808918,
            "rice paper": 33.333333333333336,
            "rice pilaf": 33.333333333333336,
            "risotto": 100.0,
            "rockfish": 75.0,
            "roll": 81.81818181818181,
            "rutabaga": 100.0,
            "salad": 68.42105263157895,
            "salami": 33.333333333333336,
            "salmon": 97.33333333333333,
            "salsa": 100.0,
            "salt": 85.29411764705883,
            "samosa": 88.88888888888889,
            "sandwich": 88.46153846153847,
            "sardine": 100.0,
            "sauce": 83.10502283105023,
            "sausage": 0.0,
            "scallion": 0.0,
            "scallop": 100.0,
            "scone": 0.0,
            "seafood": 11.11111111111111,
            "seasoned": 67.12871287128714,
            "seasoning": 85.82089552238806,
            "seasoning salt": 0.0,
            "seaweed": 50.0,
            "seed": 80.48780487804878,
            "seitan": 100.0,
            "shallot": 100.0,
            "shell": 76.92307692307692,
            "sherbet": 92.3076923076923,
            "shortening": 100.0,
            "shrimp": 96.29629629629629,
            "slider": 50.0,
            "smoothie": 69.23076923076923,
            "snack": 67.41573033707866,
            "snack kit": 100.0,
            "snapper": 100.0,
            "soda": 93.6842105263158,
            "sole": 75.0,
            "sorbet": 81.81818181818181,
            "soup": 92.5925925925926,
            "sour cream": 98.41269841269842,
            "spaghetti": 33.333333333333336,
            "spice": 16.091954022988507,
            "spinach": 97.11538461538461,
            "sports drink": 86.36363636363636,
            "spray": 0.0,
            "spread": 81.48148148148148,
            "spring roll": 100.0,
            "sprout": 100.0,
            "squash": 97.88519637462235,
            "starch": 20.0,
            "steak": 0.0,
            "stew": 27.272727272727273,
            "stir fry": 50.0,
            "stock": 75.0,
            "strawberry": 93.06930693069307,
            "stuffing": 0.0,
            "sugar": 98.79518072289157,
            "sugar substitute": 12.5,
            "supplement": 94.28571428571429,
            "sushi": 100.0,
            "sweetener": 0.0,
            "swiss chard": 100.0,
            "swordfish": 100.0,
            "syrup": 11.11111111111111,
            "taco": 66.66666666666667,
            "taco shell": 33.333333333333336,
            "tamale": 95.0,
            "tangelo": 85.71428571428571,
            "tangerine": 48.275862068965516,
            "taquito": 100.0,
            "taro": 75.0,
            "taro leaf": 50.0,
            "tater tot": 100.0,
            "tea": 84.98293515358361,
            "tempeh": 100.0,
            "thickener": 11.11111111111111,
            "ti leaf": 100.0,
            "tilapia": 100.0,
            "tofu": 96.07843137254902,
            "tomatillo": 100.0,
            "tomato": 97.88135593220339,
            "topping": 79.1044776119403,
            "tortellini": 75.0,
            "tortilla": 91.03448275862068,
            "trout": 85.71428571428571,
            "tuna": 85.8267716535433,
            "tuna salad": 0.0,
            "turkey": 86.20253164556962,
            "turnip": 100.0,
            "turnover": 100.0,

In [26]:
basic_types = ["(malformed)"] + allowed["Basic Type"]
toindex = {x: i for i, x in enumerate(basic_types)}

good_good = np.zeros(len(toindex) * 2, dtype=int)
good_wantmore = np.zeros(len(toindex) * 2, dtype=int)
gotmore_good = np.zeros(len(toindex) * 2, dtype=int)
gotmore_wantmore = np.zeros(len(toindex) * 2, dtype=int)
denominator = np.zeros(len(toindex) * 2, dtype=int)

for _, row in df.iterrows():
    want = set(row["want_Sub-Type"] or [])
    got = set(row["got_Sub-Type"] or [])
    index = toindex.get(row["got_Basic Type"], 0) * 2 + int(len(got) == 0)

    wantmore = not want.issubset(got)
    gotmore = not got.issubset(want)
    if not wantmore and not gotmore:
        good_good[index] += 1
    if wantmore and not gotmore:
        good_wantmore[index] += 1
    if not wantmore and gotmore:
        gotmore_good[index] += 1
    if wantmore and gotmore:
        gotmore_wantmore[index] += 1
    denominator[index] += 1

table = pd.DataFrame({
    "good_good": good_good,
    "good_wantmore": good_wantmore,
    "gotmore_good": gotmore_good,
    "gotmore_wantmore": gotmore_wantmore,
    "denominator": denominator,
}, index=pd.MultiIndex.from_product([pd.Index(basic_types, name="Basic Type"), pd.Index([False, True], name="empty Sub-Type")]))

In [27]:
table

                            good_good  good_wantmore  gotmore_good  \
Basic Type  empty Sub-Type
(malformed) False                  45             19            98
            True                 4500           1231             0
chicken     False                  46              9            71
            True                 1119            303             0
beef        False                  50             17            81
...                               ...            ...           ...
scallion    True                    3              0             0
bakery      False                   0              0             0
            True                    0              0             0
sea bass    False                   0              0             0
            True                    0              0             0

                            gotmore_wantmore  denominator
Basic Type  empty Sub-Type
(malformed) False                        117          279
            True                           0         5731
chicken     False                         72          198
            True                           0         1422
beef        False                         67          215
...                                      ...          ...
scallion    True                           0            3
bakery      False                          0            0
            True                           0            0
sea bass    False                          0            0
            True                           0            0

[1120 rows x 5 columns]

In [28]:
(table["good_good"] + table["good_wantmore"] + table["gotmore_good"] + table["gotmore_wantmore"] == table["denominator"]).all()

np.True_

In [29]:
prepare = (table["good_good"] / table["denominator"] * 100).to_frame("P(correct)").assign(numsamples=table["denominator"])[table["denominator"] != 0]

In [30]:
prepare

                            P(correct)  numsamples
Basic Type  empty Sub-Type
(malformed) False            16.129032         279
            True             78.520328        5731
chicken     False            23.232323         198
            True             78.691983        1422
beef        False            23.255814         215
...                                ...         ...
seafood     False            33.333333           6
            True             66.666667           3
frosting    True            100.000000           1
ti leaf     True            100.000000           1
scallion    True            100.000000           3

[704 rows x 2 columns]

In [31]:
p_subtype_correct = {
    "overall": table["good_good"].sum() / table["denominator"].sum() * 100,
    "nonempty_Sub-Type": table["good_good"].loc[:, False].sum() / table["denominator"].loc[:, False].sum() * 100,
    "empty_Sub-Type": table["good_good"].loc[:, True].sum() / table["denominator"].loc[:, True].sum() * 100,
    "byvalue_nonempty": dict(prepare["P(correct)"].loc[:, False]),
    "byvalue_empty": dict(prepare["P(correct)"].loc[:, True]),
    "numsamples_nonempty": {k: int(v) for k, v in dict(prepare["numsamples"].loc[:, False]).items()},
    "numsamples_empty": {k: int(v) for k, v in dict(prepare["numsamples"].loc[:, True]).items()},
}

In [32]:
print(json.dumps(p_subtype_correct, indent=4))

{
    "overall": 62.93221110100091,
    "nonempty_Sub-Type": 50.863821138211385,
    "empty_Sub-Type": 72.71416803953872,
    "byvalue_nonempty": {
        "(malformed)": 16.129032258064516,
        "chicken": 23.232323232323232,
        "beef": 23.25581395348837,
        "cheese": 56.93860386879731,
        "condiment": 58.17774458551157,
        "juice": 30.702598652550527,
        "pork": 60.42553191489362,
        "sauce": 59.62199312714777,
        "dessert": 52.43445692883895,
        "pepper": 73.57142857142858,
        "potato": 52.81249999999999,
        "turkey": 42.857142857142854,
        "seasoned": 72.50608272506082,
        "apple": 76.28205128205127,
        "cereal": 39.65936739659367,
        "chip": 42.26086956521739,
        "tomato": 75.77319587628865,
        "carrot": 16.666666666666664,
        "yogurt": 20.462046204620464,
        "dressing": 75.1578947368421,
        "lettuce": 73.9938080495356,
        "onion": 57.14285714285714,
        "cracker": 40.24024024024024,
        "herb": 70.94240837696336,
        "bread": 35.231316725978644,
        "milk": 51.724137931034484,
        "bean": 28.000000000000004,
        "pasta": 27.710843373493976,
        "bar": 18.244803695150118,
        "squash": 89.73214285714286,
        "vegetable": 58.371040723981906,
        "dough": 47.35202492211838,
        "snack": 18.823529411764707,
        "pastry": 46.808510638297875,
        "ice cream": 36.79245283018868,
        "orange": 50.0,
        "mix": 50.988142292490124,
        "cookie": 41.830065359477125,
        "sandwich": 37.62376237623762,
        "melon": 90.27027027027027,
        "eggs": 7.4074074074074066,
        "tortilla": 75.38461538461539,
        "entr\u00c3\u00a9e": 33.33333333333333,
        "coffee": 17.391304347826086,
        "drink": 12.903225806451612,
        "water": 44.516129032258064,
        "tea": 27.92207792207792,
        "candy": 20.833333333333336,
        "soup": 41.82692307692308,
        "muffin": 55.714285714285715,
        "oil": 75.26881720430107,
        "bun": 54.83870967741935,
        "french fry": 71.42857142857143,
        "broccoli": 30.434782608695656,
        "pear": 75.9493670886076,
        "celery": 37.03703703703704,
        "pizza": 58.333333333333336,
        "soda": 19.51219512195122,
        "cucumber": 35.0,
        "spread": 50.38167938931297,
        "cabbage": 62.5,
        "rice": 55.55555555555556,
        "roll": 42.15686274509804,
        "seasoning": 66.66666666666666,
        "base": 60.0,
        "bagel": 56.92307692307692,
        "sugar": 43.47826086956522,
        "corn": 30.0,
        "banana": 0.0,
        "peach": 0.0,
        "mushroom": 71.875,
        "salad": 34.81481481481482,
        "pineapple": 0.0,
        "topping": 42.857142857142854,
        "creamer": 68.47826086956522,
        "grape": 59.64912280701754,
        "strawberry": 0.0,
        "plant milk": 88.14814814814815,
        "vinegar": 71.42857142857143,
        "applesauce": 76.66666666666667,
        "cauliflower": 0.0,
        "nut": 62.5,
        "meatless": 38.095238095238095,
        "mandarin": 46.666666666666664,
        "spinach": 0.0,
        "spice": 68.65671641791045,
        "butter": 44.44444444444444,
        "meal kit": 33.33333333333333,
        "puree": 26.229508196721312,
        "tuna": 42.857142857142854,
        "burrito": 69.44444444444444,
        "pea": 35.41666666666667,
        "salsa": 60.0,
        "radish": 94.44444444444444,
        "french toast": 38.88888888888889,
        "pancake": 60.97560975609756,
        "beet": 100.0,
        "kale": 33.33333333333333,
        "flour": 53.125,
        "waffle": 63.1578947368421,
        "sports drink": 26.666666666666668,
        "pollock": 14.285714285714285,
        "cream cheese": 14.285714285714285,
        "fruit": 8.064516129032258,
        "noodle": 61.64383561643836,
        "supplement": 8.695652173913043,
        "olive": 44.0,
        "baby food": 85.71428571428571,
        "jicama": 95.23809523809523,
        "garlic": 33.33333333333333,
        "shrimp": 50.0,
        "salt": 12.5,
        "avocado": 27.77777777777778,
        "blueberry": 0.0,
        "paste": 72.6027397260274,
        "kiwi": 0.0,
        "margarine": 0.0,
        "salmon": 25.0,
        "meal": 20.833333333333336,
        "shell": 53.44827586206896,
        "energy drink": 0.0,
        "lemon": 0.0,
        "seed": 73.41772151898735,
        "eggplant": 50.0,
        "ravioli": 71.42857142857143,
        "biscuit": 25.0,
        "mango": 0.0,
        "peanut butter": 23.52941176470588,
        "cranberry": 0.0,
        "popcorn": 42.5,
        "cod": 22.22222222222222,
        "tilapia": 20.0,
        "honey": 0.0,
        "oat": 0.0,
        "breadstick": 52.38095238095239,
        "lamb": 37.5,
        "cream": 65.21739130434783,
        "grapefruit": 0.0,
        "tofu": 20.0,
        "lasagna": 40.42553191489361,
        "appetizer": 18.51851851851852,
        "gravy": 53.84615384615385,
        "omelette": 70.0,
        "asparagus": 0.0,
        "tangerine": 16.666666666666664,
        "raisin": 44.44444444444444,
        "patty": 35.13513513513514,
        "english muffin": 0.0,
        "chili": 20.0,
        "macaroni": 46.93877551020408,
        "popsicle": 10.0,
        "broth": 80.0,
        "ginger": 0.0,
        "crouton": 31.57894736842105,
        "edamame": 0.0,
        "lime": 0.0,
        "tamale": 62.857142857142854,
        "breadcrumb": 66.66666666666666,
        "fruit cocktail": 0.0,
        "fruit cup": 30.0,
        "corn dog": 35.714285714285715,
        "wrap": 21.428571428571427,
        "smoothie": 30.0,
        "batter": 52.94117647058824,
        "egg": 0.0,
        "cherry": 50.0,
        "pumpkin": 0.0,
        "egg roll": 73.33333333333333,
        "spring roll": 75.0,
        "extract": 52.0,
        "fish": 7.6923076923076925,
        "empanada": 70.83333333333334,
        "flatbread": 0.0,
        "filling": 72.72727272727273,
        "juice cup": 0.0,
        "wine": 50.0,
        "fruit snack": 33.33333333333333,
        "persimmon": 83.33333333333334,
        "shortening": 0.0,
        "snack kit": 0.0,
        "enchilada": 61.904761904761905,
        "crust": 62.5,
        "burger": 52.17391304347826,
        "taquito": 85.71428571428571,
        "slider": 0.0,
        "quesadilla": 93.33333333333333,
        "cornmeal": 0.0,
        "guacamole": 0.0,
        "macaroni and cheese": 0.0,
        "pretzel": 9.090909090909092,
        "artichoke": 100.0,
        "additives": 0.0,
        "catfish": 33.33333333333333,
        "turnip": 0.0,
        "grits": 25.0,
        "sorbet": 40.0,
        "ramen": 12.5,
        "lentil": 0.0,
        "turnover": 66.66666666666666,
        "potsticker": 75.0,
        "coconut": 0.0,
        "quiche": 58.333333333333336,
        "calzone": 66.66666666666666,
        "veal": 0.0,
        "protein shake": 0.0,
        "manicotti": 66.66666666666666,
        "oatmeal": 0.0,
        "tangelo": 0.0,
        "pomegranate": 50.0,
        "granola": 0.0,
        "sherbet": 16.666666666666664,
        "taco": 50.0,
        "endive": 66.66666666666666,
        "flavor": 100.0,
        "kombucha": 0.0,
        "flower": 0.0,
        "salami": 0.0,
        "clam": 0.0,
        "loaf": 25.0,
        "cornbread": 100.0,
        "italian ice": 71.42857142857143,
        "berry": 40.0,
        "blintz": 87.5,
        "crab": 33.33333333333333,
        "pickle": 0.0,
        "chard": 50.0,
        "bowl": 0.0,
        "gelato": 20.0,
        "microgreen": 0.0,
        "fruit salad": 0.0,
        "tortellini": 50.0,
        "molasses": 0.0,
        "wafer": 20.0,
        "samosa": 44.44444444444444,
        "pupusa": 87.5,
        "watermelon": 16.666666666666664,
        "flounder": 100.0,
        "chimichanga": 66.66666666666666,
        "pie": 5.0,
        "bison": 50.0,
        "meatball": 0.0,
        "trout": 100.0,
        "syrup": 25.0,
        "dumpling": 57.14285714285714,
        "dragon fruit": 0.0,
        "cone": 50.0,
        "sole": 0.0,
        "hummus": 0.0,
        "flavoring": 50.0,
        "taro": 0.0,
        "sushi": 0.0,
        "lobster": 0.0,
        "stew": 30.0,
        "chile relleno": 100.0,
        "sausage": 11.11111111111111,
        "hot dog": 33.33333333333333,
        "wrapper": 100.0,
        "jelly": 16.666666666666664,
        "pot pie": 66.66666666666666,
        "tuna salad": 0.0,
        "dip": 60.0,
        "seaweed": 100.0,
        "falafel": 0.0,
        "croissant": 7.142857142857142,
        "pepperoni": 0.0,
        "eggroll": 40.0,
        "sprout": 100.0,
        "preserve": 50.0,
        "additive": 100.0,
        "farro": 0.0,
        "kimchi": 0.0,
        "parfait": 0.0,
        "zucchini": 0.0,
        "icing": 100.0,
        "yucca": 100.0,
        "thickener": 0.0,
        "swiss chard": 0.0,
        "sugar substitute": 0.0,
        "sardine": 0.0,
        "mustard greens": 0.0,
        "gelatin": 0.0,
        "wonton": 100.0,
        "spaghetti": 25.0,
        "peanut": 0.0,
        "pierogi": 100.0,
        "kolache": 66.66666666666666,
        "starch": 0.0,
        "juice bar": 0.0,
        "hash": 0.0,
        "frittata": 0.0,
        "doughnut": 0.0,
        "stock": 75.0,
        "pinwheel": 0.0,
        "bacon": 0.0,
        "muesli": 100.0,
        "chile": 0.0,
        "scone": 0.0,
        "meatloaf": 0.0,
        "dolma": 0.0,
        "chalupa": 100.0,
        "pot roast": 0.0,
        "spray": 0.0,
        "potpie": 100.0,
        "risotto": 100.0,
        "kit": 50.0,
        "steak": 0.0,
        "entree": 0.0,
        "rice pilaf": 0.0,
        "meat": 0.0,
        "powder": 50.0,
        "stir fry": 100.0,
        "seafood": 33.33333333333333
    },
    "byvalue_empty": {
        "(malformed)": 78.52032804048159,
        "chicken": 78.69198312236287,
        "beef": 66.16600790513833,
        "cheese": 34.319526627218934,
        "condiment": 23.076923076923077,
        "juice": 70.47619047619048,
        "pork": 69.00175131348512,
        "sauce": 20.74829931972789,
        "dessert": 18.51851851851852,
        "pepper": 34.11764705882353,
        "potato": 72.0679012345679,
        "turkey": 71.99391171993912,
        "seasoned": 10.638297872340425,
        "apple": 59.77443609022557,
        "cereal": 28.6231884057971,
        "chip": 53.63636363636364,
        "tomato": 79.49640287769785,
        "carrot": 93.51464435146444,
        "yogurt": 81.68316831683168,
        "dressing": 13.157894736842104,
        "lettuce": 60.952380952380956,
        "onion": 94.07894736842105,
        "cracker": 61.72839506172839,
        "herb": 15.517241379310345,
        "bread": 67.81115879828327,
        "milk": 93.56435643564357,
        "bean": 74.65940054495913,
        "pasta": 96.7005076142132,
        "bar": 44.44444444444444,
        "squash": 73.83177570093457,
        "vegetable": 7.6923076923076925,
        "dough": 8.333333333333332,
        "snack": 25.0,
        "pastry": 21.62162162162162,
        "ice cream": 68.75,
        "orange": 78.51239669421489,
        "mix": 27.27272727272727,
        "cookie": 58.86524822695035,
        "sandwich": 33.33333333333333,
        "melon": 20.0,
        "eggs": 76.21951219512195,
        "tortilla": 53.68421052631579,
        "coffee": 82.02764976958525,
        "drink": 88.88888888888889,
        "water": 92.85714285714286,
        "tea": 64.02877697841727,
        "candy": 60.86956521739131,
        "soup": 5.714285714285714,
        "muffin": 41.0958904109589,
        "oil": 19.444444444444446,
        "bun": 43.47826086956522,
        "french fry": 86.79245283018868,
        "broccoli": 89.04109589041096,
        "pear": 85.18518518518519,
        "celery": 95.75757575757575,
        "pizza": 41.17647058823529,
        "soda": 67.78523489932886,
        "cucumber": 90.27027027027027,
        "spread": 75.0,
        "cabbage": 90.38461538461539,
        "rice": 69.90291262135922,
        "roll": 21.875,
        "seasoning": 17.97752808988764,
        "base": 0.0,
        "bagel": 84.25196850393701,
        "sugar": 85.3146853146853,
        "corn": 70.58823529411765,
        "banana": 83.97435897435898,
        "peach": 95.13888888888889,
        "mushroom": 89.62264150943396,
        "salad": 17.647058823529413,
        "green bean": 96.3963963963964,
        "pineapple": 84.67153284671532,
        "topping": 68.0,
        "creamer": 65.51724137931035,
        "grape": 70.23809523809523,
        "strawberry": 97.0,
        "plant milk": 0.0,
        "vinegar": 53.57142857142857,
        "applesauce": 87.62886597938144,
        "cauliflower": 94.33962264150944,
        "nut": 0.0,
        "meatless": 46.875,
        "mandarin": 75.86206896551724,
        "spinach": 90.0990099009901,
        "spice": 0.0,
        "butter": 84.88372093023256,
        "meal kit": 50.0,
        "tuna": 74.64788732394366,
        "burrito": 0.0,
        "pea": 78.68852459016394,
        "salsa": 80.0,
        "radish": 86.11111111111111,
        "french toast": 61.53846153846154,
        "pancake": 60.0,
        "beet": 92.92929292929293,
        "kale": 89.55223880597015,
        "flour": 36.0655737704918,
        "waffle": 67.04545454545455,
        "sports drink": 85.71428571428571,
        "pollock": 69.51219512195121,
        "cream cheese": 90.9090909090909,
        "fruit": 28.57142857142857,
        "noodle": 14.814814814814813,
        "supplement": 79.16666666666666,
        "olive": 92.15686274509804,
        "baby food": 0.0,
        "jicama": 93.44262295081968,
        "garlic": 92.1875,
        "shrimp": 78.48101265822784,
        "salt": 86.66666666666667,
        "avocado": 74.50980392156863,
        "blueberry": 100.0,
        "paste": 0.0,
        "kiwi": 96.82539682539682,
        "margarine": 93.84615384615384,
        "salmon": 45.76271186440678,
        "meal": 66.66666666666666,
        "shell": 0.0,
        "energy drink": 88.23529411764706,
        "lemon": 97.43589743589743,
        "seed": 33.33333333333333,
        "eggplant": 83.33333333333334,
        "nectarine": 100.0,
        "sour cream": 98.4126984126984,
        "biscuit": 77.04918032786885,
        "plum": 90.0,
        "mango": 100.0,
        "peanut butter": 71.11111111111111,
        "cranberry": 100.0,
        "popcorn": 50.0,
        "cod": 37.5,
        "tilapia": 62.5,
        "honey": 79.54545454545455,
        "oat": 72.72727272727273,
        "breadstick": 53.84615384615385,
        "lamb": 87.75510204081633,
        "hash brown": 92.85714285714286,
        "brussels sprout": 100.0,
        "tater tot": 100.0,
        "cream": 28.57142857142857,
        "grapefruit": 92.6829268292683,
        "tofu": 51.61290322580645,
        "lasagna": 16.666666666666664,
        "appetizer": 66.66666666666666,
        "gravy": 42.857142857142854,
        "omelette": 55.55555555555556,
        "asparagus": 100.0,
        "tangerine": 52.17391304347826,
        "raisin": 68.42105263157895,
        "patty": 0.0,
        "english muffin": 100.0,
        "apricot": 96.42857142857143,
        "chili": 41.66666666666667,
        "macaroni": 50.0,
        "popsicle": 66.66666666666666,
        "ginger": 100.0,
        "crouton": 100.0,
        "edamame": 100.0,
        "lime": 100.0,
        "tamale": 40.0,
        "breadcrumb": 50.0,
        "collard greens": 100.0,
        "fruit cocktail": 72.41379310344827,
        "fruit cup": 26.47058823529412,
        "corn dog": 33.33333333333333,
        "wrap": 75.0,
        "smoothie": 66.66666666666666,
        "egg": 64.28571428571429,
        "cherry": 54.54545454545454,
        "buttermilk": 96.875,
        "raspberry": 93.33333333333333,
        "pumpkin": 80.0,
        "egg roll": 50.0,
        "spring roll": 100.0,
        "quinoa": 93.10344827586206,
        "onion ring": 95.45454545454545,
        "corn starch": 100.0,
        "extract": 0.0,
        "fish": 60.0,
        "flatbread": 60.0,
        "hashbrown": 100.0,
        "parsnip": 95.83333333333334,
        "filling": 0.0,
        "juice cup": 100.0,
        "bok choy": 100.0,
        "wine": 0.0,
        "fruit snack": 71.42857142857143,
        "persimmon": 71.42857142857143,
        "shortening": 86.66666666666667,
        "enchilada": 0.0,
        "crust": 7.6923076923076925,
        "burger": 16.666666666666664,
        "blackberry": 80.0,
        "arugula": 61.111111111111114,
        "shallot": 100.0,
        "quesadilla": 0.0,
        "cornmeal": 90.9090909090909,
        "guacamole": 89.47368421052632,
        "duck": 95.23809523809523,
        "macaroni and cheese": 23.52941176470588,
        "fennel": 94.44444444444444,
        "pretzel": 23.25581395348837,
        "artichoke": 53.84615384615385,
        "additives": 50.0,
        "catfish": 58.82352941176471,
        "couscous": 86.66666666666667,
        "potato salad": 50.0,
        "tomatillo": 50.0,
        "turnip": 100.0,
        "grits": 66.66666666666666,
        "plantain": 75.0,
        "sorbet": 50.0,
        "ramen": 0.0,
        "lentil": 100.0,
        "baking powder": 100.0,
        "okra": 86.66666666666667,
        "pluot": 83.33333333333334,
        "coconut": 90.0,
        "quiche": 0.0,
        "hominy": 100.0,
        "date": 60.0,
        "baking soda": 100.0,
        "yeast": 75.0,
        "veal": 76.92307692307693,
        "ham": 93.33333333333333,
        "manicotti": 100.0,
        "fig": 75.0,
        "yam": 0.0,
        "food coloring": 100.0,
        "taco shell": 33.33333333333333,
        "oatmeal": 50.0,
        "tangelo": 83.33333333333334,
        "pangasius": 57.14285714285714,
        "caper": 100.0,
        "papaya": 100.0,
        "pomegranate": 20.0,
        "crab cake": 85.71428571428571,
        "granola": 57.14285714285714,
        "sherbet": 57.14285714285714,
        "cinnamon roll": 33.33333333333333,
        "endive": 33.33333333333333,
        "kombucha": 33.33333333333333,
        "watercress": 100.0,
        "flower": 33.33333333333333,
        "barley": 100.0,
        "salami": 60.0,
        "clam": 91.66666666666666,
        "polenta": 85.71428571428571,
        "loaf": 100.0,
        "cornbread": 100.0,
        "bean sprout": 84.61538461538461,
        "kohlrabi": 100.0,
        "italian ice": 20.0,
        "berry": 40.0,
        "crab": 71.42857142857143,
        "pickle": 0.0,
        "chard": 71.42857142857143,
        "leek": 87.5,
        "gelato": 100.0,
        "prune": 100.0,
        "microgreen": 40.0,
        "fruit salad": 72.72727272727273,
        "molasses": 100.0,
        "watermelon": 9.090909090909092,
        "radicchio": 80.0,
        "flounder": 50.0,
        "clementine": 25.0,
        "wax bean": 100.0,
        "pie": 0.0,
        "mahi mahi": 25.0,
        "bison": 100.0,
        "meatball": 100.0,
        "trout": 33.33333333333333,
        "syrup": 0.0,
        "dumpling": 100.0,
        "dragon fruit": 100.0,
        "cocoa powder": 83.33333333333334,
        "sweetener": 0.0,
        "cone": 0.0,
        "sole": 40.0,
        "hummus": 10.0,
        "flavoring": 33.33333333333333,
        "taro": 100.0,
        "cilantro": 33.33333333333333,
        "celery root": 60.0,
        "sushi": 0.0,
        "lobster": 100.0,
        "stew": 0.0,
        "chile relleno": 0.0,
        "sausage": 0.0,
        "hot dog": 33.33333333333333,
        "jelly": 0.0,
        "breadfruit": 100.0,
        "lychee": 75.0,
        "dip": 100.0,
        "bamboo shoot": 100.0,
        "broccolini": 100.0,
        "green onion": 100.0,
        "seaweed": 0.0,
        "falafel": 75.0,
        "croissant": 0.0,
        "pepperoni": 20.0,
        "farro": 100.0,
        "wheat berry": 100.0,
        "chicken salad": 0.0,
        "lemongrass": 0.0,
        "rutabaga": 100.0,
        "zucchini": 13.333333333333334,
        "snapper": 100.0,
        "bulgur": 0.0,
        "butter alternative": 100.0,
        "cactus": 33.33333333333333,
        "icing": 0.0,